### ISSUE TITLE
Interview To Gather Requirements

### ISSUE THREAD

**Issue by khoiphan21** [deco3500/factopia#13]

**Comment by soobin93** [comment]
Brief Information of our product.
(Concept of universe and sequence, visual aspect, rating system)
1. What is your gender?
2. As a user, do you think you would like to use this kind of application?
3. Do you think this application might be able to bring the improvement in current journalism?
4. Do you have any comment or feedback which will improve this idea?
5. Do you think there is a possibility which the visual aspect of this application might disturb users from reading news?
6. Is rating system enough to figure out the credible news and big news?
7. Do you think you will be able to quickly navigate articles of interest around?
8. What do you think of applying visual aspect of this idea to an existing forum or network?
